# Database connection URL: jdbc:postgresql://<host>:<port>/<database_name>
spring.datasource.url=jdbc:postgresql://localhost:5432/ticketing_db

# Database username
spring.datasource.username=postgres

# Database password
spring.datasource.password=shahnan

# Optional: Specify the driver class name (usually automatically detected by Spring Boot)
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: Configure Hibernate DDL-auto property for schema management
# Options include: none, create, create-drop, update, validate
spring.jpa.hibernate.ddl-auto=validate

#Closes DB connection when not in use
spring.jpa.open-in-view=false